language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - travis_retry composer self-update
  - travis_retry composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - php vendor/bin/codecept run